### your site title here

title: Daniel G. Heslep
description: PhD Candidate | Unviersity of Central Florida | 

baseurl: /gradsitedemo #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: dgheslep@knights.ucf.edu

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: "@danielheslep"
orcid: "https://orcid.org/0000-0001-9229-5085"



# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - DARC.md
      - MappingDiscordsDarkside.md
      - redirect.md
      - TheBERNapp.md


sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
